In [1]:
import numpy as np

In [2]:
S0 = 100
K = 100
r = 0.06
T = 1
N = 3
dt= T/N
u = 1.1
d = 1/u
Optiontype = "P"

# From Bottom to top array Approach

In [3]:
def Binomial_tree_AM_S_BT(S0,K,r,T,N,u,d,Optiontype = "P"):
    dt = T/N
    q = (np.exp(r*dt)-d)/(u-d)
    disc = np.exp((-r)*dt)
    
    #Stock proces st maturity
    S = np.zeros(N+1)
    for j in range(0,N+1):
        S[j] = S0*(u**j)*(d**(N-j))
        
    print(S)
    
    #Option Payoffs
    P = np.zeros(N+1)
    for j in range(0,N+1):
        P[j] = max(K-S[j],0)
    print(P)
        
    #Backward discounting pricing
    for i in np.arange(N-1,-1,-1):
        for j in range(0,i+1):
            S = S0 * (u**j) * (d**(i-j))
            
            P[j] = disc*(q*P[j+1]+(1-q)*P[j])
            
            P[j] = max(P[j], (K-S))
        print(P)
    
    
    return P[0]

In [24]:
Binomial_tree_AM_S_BT(S0,K,r,T,3,u,d,Optiontype = "P")

[ 75.13148009  90.90909091 110.         133.1       ]
[24.86851991  9.09090909  0.          0.        ]
[17.3553719   3.72469241  0.          0.        ]
[9.23564829 1.52606669 0.         0.        ]
[4.65458875 1.52606669 0.         0.        ]


4.654588754602527

# From Top to Bottom Array Approach

In [21]:
def Binomial_tree_AM_S_TB(S0,K,r,T,N,u,d,Optiontype = "P"):
    dt = T/N
    q = (np.exp(r*dt)-d)/(u-d)
    disc = np.exp((-r)*dt)
    
    #Stock proces st maturity
    S = np.zeros(N+1)
    for j in np.arange(N,-1,-1):
        S[j] = S0 *(u**(N-j))*(d**j)
        print(S[j])
        
    print(S)
    
    #Option Payoffs
    P = np.zeros(N+1)
    for j in np.arange(N,-1,-1):
        P[j] = max(K-S[j],0)
    print(P)
        
    #Backward discounting pricing
    for i in np.arange(N-1,-1,-1):
        for j in np.arange(i,-1,-1):
            S = S0 * (u**j) * (d**(i-j))
            
            P[i-j] = disc*(q*P[i-j]+(1-q)*P[i-j+1])
            
            P[i-j] = max(P[i-j], (K-S))
        print(P)
    
    
    return P[0]

In [23]:
Binomial_tree_AM_S_TB(S0,K,r,T,3,u,d,Optiontype = "P")

75.13148009015777
90.9090909090909
110.00000000000001
133.10000000000005
[133.1        110.          90.90909091  75.13148009]
[ 0.          0.          9.09090909 24.86851991]
[ 0.          3.72469241 17.3553719  24.86851991]
[ 1.52606669  9.23564829 17.3553719  24.86851991]
[ 4.65458875  9.23564829 17.3553719  24.86851991]


4.654588754602527

# Vector Method


In [7]:
def Binomial_tree_Fast(S0,K,r,T,N,u,d,Optiontype = "P"):
    dt = T/N
    q = (np.exp(r*dt)-d)/(u-d)
    disc = np.exp((-r)*dt)
    
    #Stock proces st maturity
    S = S0 *(d**np.arange(N,-1,-1)) * (u**np.arange(0,N+1,1))
        
    print(S)
    
    #Option Payoffs
    P = np.maximum(K-S,0)
    print(P)
        
    #Backward discounting pricing
    for i in np.arange(N-1,-1,-1):
        
        S = S0 *(d**np.arange(i,-1,-1)) * (u ** np.arange(0,i+1,1))

        P[0:i+1] = disc*(q*P[1:i+2]+(1-q)*P[0:i+1])
        P = P[:-1]
        P = np.maximum(P, (K-S))
        print(P)
    
    
    return P[0]

In [8]:
Binomial_tree_Fast(S0,K,r,T,N,u,d,Optiontype = "P")


[ 75.13148009  90.90909091 110.         133.1       ]
[24.86851991  9.09090909  0.          0.        ]
[17.3553719   3.72469241  0.        ]
[9.23564829 1.52606669]
[4.65458875]


4.654588754602527